### ISSUE TITLE
Error while optimizing JPG file

### ISSUE THREAD

**Issue by 1024mb** [devedse/DeveImageOptimizerWPF#12]
Just got multiple errors with this same message, all the files are JPG, unfortunately I can't share the files:

```
Exception happened when optimizing or comparing the image:
System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at ExifLibrary.JPEGFile.ReadExifAPP1()
   at ExifLibrary.JPEGFile..ctor(MemoryStream stream, Encoding encoding, Boolean readTrailingData)
   at ExifLibrary.ImageFile.FromStreamInternal(MemoryStream stream, Encoding encoding)
   at ExifLibrary.ImageFile.FromStreamAsync(Stream stream, Encoding encoding)
   at ExifLibrary.ImageFile.FromFileAsync(String filename, Encoding encoding)
   at ExifLibrary.ImageFile.FromFileAsync(String filename)
   at DeveImageOptimizer.ImageOperations.ImageExifComparer.AreImageExifDatasEqual(String image1Path, String image2Path)
   at DeveImageOptimizer.ImageOperations.ImageComparer.<>c__DisplayClass0_0.<<AreImagesEqualAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DeveImageOptimizer.FileProcessing.FileOptimizerProcessor.OptimizeFile(OptimizableFile file)
```

**Comment by devedse** [comment]
Hmm I'll look into it

**Comment by 1024mb** [comment]
I have been testing some of my public files and I just got the same error message with one, here it is (zipped just in case): 
[1399751938250.zip](https://github.com/devedse/DeveImageOptimizerWPF/files/10326642/1399751938250.zip)

**Comment by devedse** [comment]
Apparently it's an issue with the EXIF comparison tool I'm using, I've created an issue in his Github:
https://github.com/oozcitak/exiflibrary/issues/111

**Comment by 1024mb** [comment]
> Apparently it's an issue with the EXIF comparison tool I'm using, I've created an issue in his Github:
> [oozcitak/exiflibrary#111](https://github.com/oozcitak/exiflibrary/issues/111)

Thanks, hopefully this gets fixed though it has only happened with some files.

> What `save failed files` does is store the failed file as `{filename}_Failed.jpg`. This makes investigating what went wrong a bit easier. It won't ever overwrite the destination file though of the optimization failed.

Oh, right, I just realized I forgot to add something to my previous comment. I meant that when I get those errors and "save failed files" is enabled the (failed) files aren't saved, I got no `{filename}_Failed.jpg`, that's why I was asking that.

**Comment by T0T4R4** [comment]
I have the same error on an photo taken by an android phone and which Exif data has been updated by this library. When loading this same image from my webapp, the error is thrown.

**Comment by devedse** [comment]
Can you guys maybe post in the GitHub issue I've mentioned? Maybe the owner of the library I'm using for the exif data can try to fix it.

**Comment by T0T4R4** [comment]
I've got the same error using directly the ExifLib library - added a comment to your post
